// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaAPI.DB;

namespace PesquisaAPI.Migrations
{
    [DbContext(typeof(PesquisaSatisfacaoContext))]
    partial class PesquisaSatisfacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PesquisaAPI.Models.InformacoesRespostas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(3500)");

                    b.Property<int>("PerguntasId")
                        .HasColumnType("int");

                    b.Property<int>("RespostasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerguntasId");

                    b.HasIndex("RespostasId");

                    b.ToTable("Informacoes");
                });

            modelBuilder.Entity("PesquisaAPI.Models.Perguntas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Pesquisa");
                });

            modelBuilder.Entity("PesquisaAPI.Models.Respostas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Resposta")
                        .HasColumnType("varchar(3500)");

                    b.Property<string>("TipoCampo")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("PesquisaAPI.Models.InformacoesRespostas", b =>
                {
                    b.HasOne("PesquisaAPI.Models.Perguntas", "Perguntas")
                        .WithMany()
                        .HasForeignKey("PerguntasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaAPI.Models.Respostas", "Respostas")
                        .WithMany("Informacoes")
                        .HasForeignKey("RespostasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
